# Generated by Django 4.1.1 on 2022-09-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='t_money',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
